on:
  pull_request:
  push:
    branches:
    - unified-runtime

jobs:
  ci:
    env:
      no_proxy: devtools.intel.com
      DEBIAN_FRONTEND: noninteractive
      ONEAPI_PASSPHRASE: ${{ secrets.ONEAPI_PASSPHRASE }}
      PUBLISH_CMD: python3 oneapi-publish.py publish --html ../html --doc unified-runtime  --version 0.5
      ACTIVATE: /localdisk/work/rscohn1/github-runners/venv/doc/bin/activate
    runs-on: dds-base
    steps:
    - uses: actions/checkout@v2
    - name: Checkout scripts
      uses: actions/checkout@v2
      with:
        ref: main
        path: scripts
    - name: Install publishing pre-requisites
      run: |
        source ${ACTIVATE}
        cd scripts
        python3 oneapi-publish.py setup
    - name: Publish to pre-production
      if: ${{ github.ref != 'refs/heads/unified-runtime' }}
      run: |
        source ${ACTIVATE}
        cd scripts
        ${PUBLISH_CMD}
    - name: Publish to production
      if: ${{ github.ref == 'refs/heads/unified-runtime' }}
      run: |
        source ${ACTIVATE}
        cd scripts
        ${PUBLISH_CMD} --prod
